name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-13  # Mac runner con Xcode

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.2.app

      - name: Dar permisos de ejecución al script
        run: chmod +x ./run_tests.sh

      - name: Ejecutar pruebas
        run: ./run_tests.sh


